BaseUrl= "https://www.yunspace.com/"
LanguageCode= "en-us"
Title= "YunSpace"
paginate = 5
DisqusShortname = "yunzhilin"
Copyright = "All rights reserved - 2015"
canonifyurls = true
theme = "casper"

[params]
  description = "Beyond the Clouds"
  cover = "images/cover.jpg"
  author = "Yun Zhi Lin"
  authorlocation = "Sydney, Australia"
  authorwebsite = "https://www.yunspace.com"
  bio= "my bio"
  logo = "images/yun_stamp_trans.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "yunspace"
  twitterName = "yunzhilin"
  # facebookName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Github"
  weight = 100
  pre = "<h3>Follow me</h3>"
  url = "https://github.com/yunspace"

[[menu.main]]
  name = "Twitter"
  weight = 101
  url = "https://twitter.com/yunzhilin"

[[menu.main]]
  name = "LinkedIn"
  weight = 101
  url = "https://au.linkedin.com/in/yunzhilin"
