BaseUrl= "https://www.yunspace.com/"
LanguageCode= "en-us"
Title= "YunSpace"
paginate = 5
DisqusShortname = "yunzhilin"
Copyright = "All rights reserved - 2015"
canonifyurls = true

[params]
  description = "Life amongst the Clouds"
  cover = "img/cover.jpg"
  author = "Yun Zhi Lin"
  authorlocation = "Sydney, Australia"
  authorwebsite = "https://www.yunspace.com"
  bio= "my bio"
  logo = "img/yun_stamp_trans.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "yunspace"
  twitterName = "yunzhilin"
  # facebookName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Github repos"
  weight = 100
  pre = "<h3>Follow me</h3>"
  url = "https://github.com/vjeantet"

[[menu.main]]
  name = "Twitter timeline"
  weight = 101
  url = "https://twitter.com/vjeantet"

[[menu.main]]
  name = "Flipboard magazines"
  weight = 102
  url = "https://flipboard.com/@vjeantet"

[[menu.main]]
  name = "Keybase (secure msg)"
  weight = 109
  pre = "<h3>Contact me</h3>"
  url = "https://Keybase.io/vjeantet"
